apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"api","namespace":"default"},"spec":{"selector":{"matchLabels":{"run":"api"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"run":"api"}},"spec":{"containers":[{"env":[{"name":"SPRING_DATASOURCE_URL","value":"jdbc:postgresql://10.101.112.5:5432/dev"},{"name":"SPRING_DATASOURCE_DB","value":"dev"},{"name":"SPRING_DATASOURCE_USERNAME","value":"dev"},{"name":"SPRING_DATASOURCE_PASSWORD","value":"oWUm02jbtsiXh%Z"},{"name":"SPRING_DATASOURCE_DIALECT","value":"org.hibernate.dialect.PostgreSQL94Dialect"},{"name":"FIREBASE_KEY_LOCATION","value":"/app/firebase.json"}],"image":"gcr.io/d-printing-dev/threedprintingservice:1.1","imagePullPolicy":"IfNotPresent","name":"threedprintingservice","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app","name":"firebase","readOnly":true}]}],"restartPolicy":"Always","volumes":[{"name":"firebase","secret":{"defaultMode":420,"secretName":"firebase"}}]}}}}
  creationTimestamp: "2020-03-29T19:56:20Z"
  generation: 8
  labels:
    run: api
  name: api
  namespace: default
  resourceVersion: "562945"
  selfLink: /apis/apps/v1/namespaces/default/deployments/api
  uid: ad074667-1f64-4aeb-ac13-6b6084ce4338
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: api
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://10.101.112.5:5432/dev
            - name: SPRING_DATASOURCE_DB
              value: dev
            - name: SPRING_DATASOURCE_USERNAME
              value: dev
            - name: SPRING_DATASOURCE_PASSWORD
              value: oWUm02jbtsiXh%Z
            - name: FIREBASE_KEY_LOCATION
              value: /firebase/firebase.json
            - name: CORS_ORIGINS
              value: http://localhost:8080,http://localhost:3000,https://3dtomeds.com
          image: gcr.io/GKE_PROJECT/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          name: threedprintingservice
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /firebase
              name: firebase
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: firebase
          secret:
            defaultMode: 420
            secretName: firebase
status:
  availableReplicas: 1
  collisionCount: 1
  conditions:
    - lastTransitionTime: "2020-03-29T20:10:59Z"
      lastUpdateTime: "2020-03-29T20:10:59Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-03-29T19:56:20Z"
      lastUpdateTime: "2020-03-29T23:25:58Z"
      message: ReplicaSet "api-7d4dd9bb4f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
